package machine;

public enum CoffeeMachineStatus {
    CHOOSING_AN_ACTION_TO_START,
    CHOOSING_VARIANT_OF_COFFEE,
    MAINTENANCE_CHECKING_INVENTORY,
    MAINTENANCE_FILLING,
    MAINTENANCE_SHUTDOWN,
    MAINTENANCE_TAKING_MONEY
}